spring.application.name=database.demo
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3307/demo_java
spring.datasource.username=root
spring.datasource.password=

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.jdbc=DEBUG

server.ssl.enabled=true
server.ssl.key-store=classpath:demo-ssl.p12
server.ssl.key-store-password=123456
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=demo-ssl


